Zusammenfassung Import
stadt-bielefeld/auik pull request #105
Opened 2022-10-14 13:48 UTC by awoestmann

Hiermit sollte #77 gelöst sein:

* Beide Importer sind jetzt in einem einzelnen Modul zusammengefasst ("Import" in der Kategorie "Labor")
* Die Art des Imports kann über eine Combobox ausgewählt werden
* Die Fehlerbehandlung bzw. die Ergebnisanzeige aus dem Sielhautimport sollte jetzt bei beiden Importtypen einheitlich implementiert sein

2022-10-17 11:07 UTC, Tilkiyim commented
in der GUI taucht kein Dropdownmenü etc auf. Die Importer haben sich in der Oberfläche nicht verändert.

2022-10-24 07:00 UTC, awoestmann commented
> in der GUI taucht kein Dropdownmenü etc auf. Die Importer haben sich in der Oberfläche nicht verändert.

Die alten Importer sind tatsächlich auch unverändert. Der neue Importer ist in einem neuen Modul das über die `auik.properties `dann ggf. noch eingebunden werden muss. Also bspw. mit:

`auik.system.module=Import, ...`

2022-10-24 09:06 UTC, Tilkiyim requested changes
Import funktioniert wunderbar. 
Kleinen Anpassungswunsch hätte ich noch:
Die Fehlermeldungen wenn eine falsche Datei ausgewählt sind unterschiedliche bei Sielhaut/Abwasser.

2022-10-26 07:34 UTC, awoestmann commented
An der Stelle habe ich die alten Importerfunktionen soweit wie möglich übernommen, daher verhalten sich die Importer unterschiedlich beim Einlesen von ungültigen Dateien. Mit 82cb170 habe ich den AbwasserImporter nochmal angepasst, so dass eine entsprechende Fehlermeldung anstelle der Warnung kommt wenn die Eingabedatei keine einzige gültige Zeile enthält.

2022-10-27 10:33 UTC, Tilkiyim approved these changes
Super. Danke!

2022-10-27 11:05 UTC, awoestmann commented
Ist hier jetzt noch ein Punkt offen oder kann der PR in den master gemerged werden?

2022-10-27 11:21 UTC, Tilkiyim commented
Kann gemerged werden

2022-10-27 12:14 UTC, merged